### ISSUE TITLE
SVG assets

### ISSUE THREAD

**Issue by mdshw5** [total-impact/total-impact-webapp#115]
It would be nice (for embedding a profile badge) to supply your logo assets in SVG or similar vector art. Possible?

**Comment by jasonpriem** [comment]
We don't have an SVG version handy, but there's quite a large raster version at https://impactstory.org/logo. There's also a code snippet you can use to embed a badge on a profile, if you log in and go to https://impactstory.org/settings/embed.

Let me know if you still need a vector version though. Perhaps you want a 100-meter Impactstory logo for the side of your blimp? Or to wrap a huge Impactstory logo [around the Reichstag?](http://christojeanneclaude.net/projects/wrapped-reichstag#.VLINo2TF8z8) Either way, you've got our approval and support...let us know and we can probably dig up something appropriately vectory.
